---
id: Release
name: Release
full: Component release library
description: Tools necessary to create the Horde distribution packages.
list: dev
type: library
homepage: https://www.horde.org/libraries/Horde_Release
authors:
  -
    name: Jan Schneider
    user: jan
    email: jan@horde.org
    active: true
    role: lead
version:
  release: 4.0.0alpha1
  api: 4.0.0alpha1
state:
  release: alpha
  api: alpha
license:
  identifier: LGPL-2.1
  uri: http://www.horde.org/licenses/lgpl21
dependencies:
  required:
    php: ^5.3 || ^7
    pear:
      pear.horde.org/Horde_Exception: ^2
      pear.horde.org/Horde_Http: ^2
      pear.horde.org/Horde_Mail: ^2
      pear.horde.org/Horde_Mime: ^2
      pear.horde.org/Horde_Rpc: ^2
      pear.horde.org/Horde_Serialize: ^2
      pear.horde.org/Horde_Util: ^2
  optional:
    pear:
      pear.horde.org/Horde_Test: ^2.1
